name: "Build & Upload Resource Pack"

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      #- name: Get Tag
      #  id: tag
      #  uses: dawidd6/action-get-tag@v1

      - name: Build & Upload Pack
        uses: Sindercube/Packr@main
        with:

          filename: pack.zip
          parts: |
            test_pack/*
          output-directory: build/ 
          optimize-files: true
          minecraft-versions: |
            1.18.2

          github-repo: 'Soumeh/Resource-Packager-Testing'
          modrinth-id: 'WXrOGDBd'
          curseforge-id: '830844'

          release-name: ${{ github.event.release.name }}
          release-version: ${{ github.event.release.tag_name }} #${{ steps.tag.outputs.tag }}
          changelog: ${{ github.event.release.body }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }} # https://modrinth.com/settings/account
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }} # https://www.curseforge.com/account/api-tokens
