name: "Build & Upload Resource Pack"

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:

      - name: Build & Upload Pack
        uses: Sindercube/Packr@main
        with:

          filename: pack.zip
          parts: |
            test_pack/*
          output-directory: build/ 
          optimize-files: true
          minecraft-versions: |
            1.18.2

          modrinth-id: 'WXrOGDBd'
          curseforge-id: '836811'
          github-repo: ${{ github.event.repository.full_name }}

          release-name: ${{ github.event.release.name }}
          release-version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
